AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7

Layout/EmptyLineAfterGuardClause:
  Enabled: false

# disable for rspec blocks
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

inherit_from: .rubocop_todo.yml

