version: 2.1

orbs:
  slack: circleci/slack@3.4.1

aliases:
  _defaults: &defaults
    working_directory: &working_directory ~/repo
    docker:
      - image: circleci/ruby:2.6.5-node-browsers

  _restore-cache: &restore-cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

  _install-dependencies: &install-dependencies
    run:
      name: install dependencies
      command: |
        bundler_version=$(cat Gemfile.lock | tail -1 | tr -d " ")
        gem install bundler -v $bundler_version
        bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle

  _save-cache: &save-cache
    save_cache:
      key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      paths:
        - ./vendor/bundle

  _rubocop: &rubocop
    run:
      name: Rubocop
      command: bundle exec rubocop

  _rspec: &rspec
    run:
      name: RSpec
      command: |
        mkdir /tmp/test-results
        TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
          circleci tests split --split-by=timings)"

        bundle exec rspec \
          --format progress \
          --format RspecJunitFormatter \
          --out /tmp/test-results/rspec.xml \
          $TEST_FILES
      when: always

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore-cache
      - *install-dependencies
      - *save-cache

  hold-deploy:
    <<: *defaults
    steps:
      - slack/approval:
          message: "Awaiting approval for deployment"
          mentions: "U34FHL074"

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - slack/notify:
          message: "Deployment of master to production started..."
          mentions: "U34FHL074"

  rubocop:
    <<: *defaults
    steps:
      - checkout
      - *restore-cache
      - *install-dependencies
      - *save-cache
      - *rubocop

  rspec:
    <<: *defaults
    steps:
      - checkout
      - *restore-cache
      - *install-dependencies
      - *save-cache
      - *rspec
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - rubocop:
          requires:
            - build
      - rspec:
          requires:
            - build
      - hold-deploy:
          type: approval
          requires:
            - rubocop
            - rspec
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - hold-deploy
          filters:
            branches:
              only:
                - master
