# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

executors:
  ruby-2.5.3:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers

references:
  build-container: &build-container
    working_directory: ~/repo
    executor: ruby-2.5.3

  checkout-app: &checkout-app
    <<: *build-container
    steps:
      - checkout

  build-app: &build-app
    <<: *checkout-app
    steps:
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler -v 1.16.2
            bundle _1.16.2_ install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

jobs:
  build:
    <<: *build-app

  brakeman:
    <<: *checkout-app
    steps:
      - run:
          name: run brakeman
          command: echo 'running brakeman'

  rubocop:
    <<: *checkout-app
    steps:
      - run:
          name: run rubocop
          command: echo 'running rubocop'

  rspec:
    <<: *build-app
    steps:
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --out /tmp/test-results/rspec.xml \
              $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - brakeman:
          requires:
            - build
      - rubocop:
          requires:
            - build
      - rspec:
          requires:
            - build
