name: Test action

on: [delete]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a multi-line script
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"

          echo '--------JSON------------'
          echo $(jq . $GITHUB_EVENT_PATH)
          echo '--------JSON------------'

          echo '--------------------'
          echo $(env)
          echo '--------------------'
